// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2pKjWeRoD5Rg6uEesxaqmmAInWnyOH2A',
    appId: '1:334203762013:web:5107e3495e9c97fdfa24b4',
    messagingSenderId: '334203762013',
    projectId: 'login-auth-55f5e',
    authDomain: 'login-auth-55f5e.firebaseapp.com',
    storageBucket: 'login-auth-55f5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWQ4W8lEfxQFR_DRr6-skRouiDU6Y1MMY',
    appId: '1:334203762013:android:dae01fad57720623fa24b4',
    messagingSenderId: '334203762013',
    projectId: 'login-auth-55f5e',
    storageBucket: 'login-auth-55f5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Uy3sH6FiWbc-3D8GDJArZ3QrcLGKsPI',
    appId: '1:334203762013:ios:4e1ec64688239cc3fa24b4',
    messagingSenderId: '334203762013',
    projectId: 'login-auth-55f5e',
    storageBucket: 'login-auth-55f5e.appspot.com',
    iosClientId: '334203762013-494qp3skhfk7i48l6u1qn9nn05mm3o69.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiKuisMatematika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Uy3sH6FiWbc-3D8GDJArZ3QrcLGKsPI',
    appId: '1:334203762013:ios:4e1ec64688239cc3fa24b4',
    messagingSenderId: '334203762013',
    projectId: 'login-auth-55f5e',
    storageBucket: 'login-auth-55f5e.appspot.com',
    iosClientId: '334203762013-494qp3skhfk7i48l6u1qn9nn05mm3o69.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiKuisMatematika',
  );
}
